### ISSUE TITLE
If the file size exceeds 1G, an error will be reported

### ISSUE THREAD

**Issue by weedsboy** [Richienb/sha1-file#2]
If the file size exceeds 1G, an error will be reported

const hash = sha1File.sync(path)
![20201201175751](https://user-images.githubusercontent.com/7411776/100725252-c5e8a500-33fe-11eb-907d-10274730ffa2.png)

**Comment by Richienb** [comment]
That's an inevitability with synchronously reading a file into memory. I recommend using the asynchronous API that streams it instead.

**Comment by weedsboy** [comment]
> That's an inevitability with synchronously reading a file into memory. I recommend using the asynchronous API that streams it instead.

thank you!
